name: "Deploy Terraform"
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key }}
          aws-region: eu-west-2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DW_USER: ${{ secrets.DW_USER }}
          DW_NAME: ${{ secrets.DW_NAME }}
          DW_PORT: ${{ secrets.DW_PORT }}
          DW_HOST: ${{ secrets.DW_HOST }}
          DW_PASSWORD: ${{ secrets.DW_PASSWORD }}
        run: 
          terraform init 

      - name: Terraform plan
        working-directory: terraform
        
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DW_USER: ${{ secrets.DW_USER }}
          DW_NAME: ${{ secrets.DW_NAME }}
          DW_PORT: ${{ secrets.DW_PORT }}
          DW_HOST: ${{ secrets.DW_HOST }}
          DW_PASSWORD: ${{ secrets.DW_PASSWORD }}
        run: 
            terraform plan -input=false -var 'db_host=$DB_HOST' -var 'db_name=$DB_NAME'  -var 'db_user=$DB_USER' -var 'db_port=$DB_PORT' -var 'db_password=$DB_PASSWORD' -var 'dw_host=$DW_HOST' -var 'dw_name=$DW_NAME' -var 'dw_user=$DW_USER' -var 'dw_port=$DW_PORT' -var 'dw_password=$DW_PASSWORD'
      - name: Terraform Apply
        working-directory: terraform
        
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DW_USER: ${{ secrets.DW_USER }}
          DW_NAME: ${{ secrets.DW_NAME }}
          DW_PORT: ${{ secrets.DW_PORT }}
          DW_HOST: ${{ secrets.DW_HOST }}
          DW_PASSWORD: ${{ secrets.DW_PASSWORD }}
        run: terraform apply -auto-approve -input=false -var 'db_host=$DB_HOST' -var 'db_name=$DB_NAME'  -var 'db_user=$DB_USER' -var 'db_port=$DB_PORT' -var 'db_password=$DB_PASSWORD' -var 'dw_host=$DW_HOST' -var 'dw_name=$DW_NAME' -var 'dw_user=$DW_USER' -var 'dw_port=$DW_PORT' -var 'dw_password=$DW_PASSWORD'