name: 'Python Test'
on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
    run-checks:
        runs-on: ubuntu-latest
        environment: DB
        env: 
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: install requirements
              run: make requirements

            - name: run Security checks
              run: make security-test

            - name: run autopep8
              run: make run-autopep

            - name: run Flake checks
              run: make run-flake

            - name: run Coverage Checks
              run: make check-coverage

    run-unit-tests:
        runs-on: ubuntu-latest
        environment: DB
        env: 
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        needs: run-checks
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: install requirements
              run: make requirements

            - name: unit tests
              run: make unit-test

